### ISSUE TITLE
FindMatlab.cmake does not find matlab 2018a

### ISSUE THREAD

**Issue by carmagnole** [G-Node/nix-mx#172]
I am trying to build nix-mx on MacOSX for MATLAB 2018a. Got the error message that the computing environment is not found, and I need to install matlab

**Comment by jgrewe** [comment]
dear @carmagnole the issue is most likely related to lines  https://github.com/G-Node/nix-mx/blob/044c39ef43aeced4e259fb5a5b7c16af748391ad/cmake/FindMATLAB.cmake#L43 and https://github.com/G-Node/nix-mx/blob/044c39ef43aeced4e259fb5a5b7c16af748391ad/cmake/FindMATLAB.cmake#L129. 
As a quick fix please add "9.4" to the front of the list in line 43 and "2018a" in line 129. This should enable cmake to find it.  

I do not have a Matlab 2018a version available right now so I cannot test. Let us know if this works, there are any other issues and if the tests pass :)

**Comment by dorahermes** [comment]
Thank you for posting this! This issue comes up again with Matlab 2019a and is fixed by adding the suggested lines 43 and 129 - it might be useful to add to the instructions page?

**Comment by jgrewe** [comment]
@dorahermes thank you for the suggestion. I included a statement into the README. Feel free to leave a comment in the respective pull request (#175)
